# Generated by Django 4.0.6 on 2022-07-12 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_store_app', '0002_rename_bike_porducer_bike_bike_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 17, 40, 28, 54678)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 17, 40, 28, 55685)),
        ),
    ]
