# Generated by Django 4.0.6 on 2022-07-12 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_store_app', '0003_alter_mycart_added_date_alter_myorder_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='bike_id',
            new_name='bike',
        ),
        migrations.RenameField(
            model_name='myorder',
            old_name='bike_id',
            new_name='bike',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='bikeid',
            new_name='bike',
        ),
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 18, 43, 26, 700933)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 18, 43, 26, 700933)),
        ),
    ]
