# Generated by Django 4.0.6 on 2022-07-12 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_store_app', '0004_rename_bike_id_mycart_bike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 18, 46, 54, 445343)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 18, 46, 54, 445343)),
        ),
    ]
