# Generated by Django 4.0.6 on 2022-07-13 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_store_app', '0008_alter_bike_image_alter_mycart_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 21, 0, 47, 946003)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 21, 0, 47, 946003)),
        ),
    ]
